services:
  # The Database Service
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=incident_logbook
    ports:
      - "5432:5432"  # Exposed for your local viewing tools (DBeaver/TablePlus)

  # The API Service (We will build this next)
  web:
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/incident_logbook
    depends_on:
      - db

volumes:
  postgres_data: